### ISSUE TITLE
Fix login path

### ISSUE THREAD

**Issue by daniepusb** [PetCare-Manager/petcaremanager-backend-python#10]
Me parece que la ruta para  **/api/login**
debería ser **/api/auth/login**

¿Qué piensan ustedes?
@diegoguaman 
@Siddharta314

**Comment by diegoguaman** [comment]
Le he añadido una prioridad inferior porque ahora mismo terminar con la primero hostoria de usuario es mas importante.
Si hay que cambiarlo, me dices

**Comment by Siddharta314** [comment]
Importante coordinar con el frontend para cambiarlo alli también y que no deje de funcionar

**Comment by daniepusb** [comment]
creé el PR para cuando queramos cambiar la ruta.
`Fix/69 fix login path now should be api auth login #70`

PD: Creo que valdría el esfuerzo crear un archivo donde colocar estas rutas y que desde allí solo exportar como constarntes. Luego lo hablamos. sigue siendo Prioridad baja


@diegoguaman 
@Siddharta314
